version: "3"
services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_MASTER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_MASTER_PASSWORD}
    ports:
      - "5432:5432"